### PR TITLE
Fixed Missing Duo3DConfig.h Problem.

### PR DESCRIPTION
**Pull request by fangchangma**
Fixed the Duo3DConfig.h problem caused by missing dependencies settings in CMakeLists.txt

### CODE REVIEW

**Comment by dbolkensteyn** [comment]
See issue #2, it seems that the root cause is a missing executable flag on `duo3d_driver/cfg/Duo3D.cfg`

**Comment by fangchangma** [comment]
> See issue #2, it seems that the root cause is a missing executable flag on duo3d_driver/cfg/Duo3D.cfg

The permission problem should be fixed by running the command `chmod a+x cfg/Duo3D.cfg` as instructed on the README file, and therefore has nothing to do with this pull request. See the discussion under #2 for details. 

This pull request fixes the compilation error of "can not find Duo3DConfig.h" related to dynamic reconfiguration in ROS.

**Comment by emreay-** [comment]
Thanks for the fix @fangchangma, I wonder why this pull request is still open and not merged.

**Comment by dbolkensteyn** [comment]
Most likely because Duo3D isn't exactly alive... (it's up to @duo3d to merge or reject this PR).

**Pull request merged**
